### PR TITLE
Added PlayerList fix for death check

### LINKED ISSUE #910: PlayerList showing players that left
PlayerList checks if death history exists, then returns
- alivePlayers: true if not dead and not left
- deadPlayers: true if dead and not left

However, if the death history of that player does not exist, it automatically returns true (or false for dead)

New check should be to have a default `isDead = false`, then change value based on player's death status, then return `!isDead && !left` (or `isDead` for dead)

### PR DESCRIPTION
**Pull request by ghost**
Resolves #910

### CODE REVIEW

**Review by Giga1396 — APPROVED** [review]

File: react_main/src/pages/Game/Game.jsx [hunk 1]
```diff
@@ -1868,12 +1868,19 @@ export function PlayerList(props) {
...
     const stateViewingInfo = history.states[props.stateViewing];
     const alivePlayers = Object.values(props.players).filter(p => {
-        if (props.stateViewing > -1 && stateViewingInfo.deaths[p.id]) {
-            return !stateViewingInfo.deaths[p.id].dead && !p.left;
+        let isDead = false;
+        if (stateViewingInfo.deaths[p.id]) {
+            isDead = stateViewingInfo.deaths[p.id].dead;
         }
-        return true;
+        return !isDead && !p.left;
```
Comment (pikulet) [inline react_main/src/pages/Game/Game.jsx:1875]: I personally feel that adding support for reviewing old games is overkill, unless it happens frequently

File: react_main/build/asset-manifest.json [hunk 2]
```diff
@@ -1,26 +1,26 @@
 {
   "files": {
     "main.css": "/static/css/main.a2ca88fb.chunk.css",
```
Comment (pikulet) [inline react_main/build/asset-manifest.json:3]: always react build in a separate commit, you can disable squash merging if you don't want to make another PR

File: react_main/src/pages/Game/Game.jsx (hunk 1 above)
Comment (minokr) [reply react_main/src/pages/Game/Game.jsx:1875]: This change was for new games, because deaths aren't initialized on Pregame

So for Pregame player list, it needs to check if deaths for playerIds exists anyway

All old games are also compatible with new history system, they just have a nulled time of death value

File: react_main/build/asset-manifest.json (hunk 2 above)
Comment (minokr) [reply react_main/build/asset-manifest.json:3]: I see, it would probably best for a "checkpoint" in commit list for what front end changes have been built

I started combining it with new PRs because having a separate PR to be approved for a react build after front-end changes seemed a bit tedious.

I think I'll probably create a PR for react builds if it follows multiple non-urgent front-end changes, otherwise an unsquashed PR with build for urgent hotfixes and/or large front-end changes from here on.

Thank you for the suggestion!
