### PR TITLE
fix: caroler is able to carol janitor

### LINKED ISSUE #752: bug(carol): janitor did not get carol n0
https://beyondmafia.com/game/dqnangs2v/review

### PR DESCRIPTION
**Pull request by pikulet**
Fixes #752

### CODE REVIEW

File: Games/types/Mafia/roles/cards/Carol.js [hunk 1]
```diff
@@ -25,7 +25,8 @@ module.exports = class Carol extends Card {
                             if (
                                 action.actors.indexOf(this.target) != -1 &&
                                 action.priority < this.priority &&
-                                !action.hasLabel("hidden")
+                                !action.hasLabel("hidden") &&
+                                action.target != "No"
```
Comment (pikulet) [inline Games/types/Mafia/roles/cards/Carol.js:29]: this means that all boolean meetings have the connotation that "no" = not visiting

**Review by starryburst — APPROVED** [review]
