### PR TITLE
feat: instant meetings reset kicks [fixes reset kicks]

### LINKED ISSUE #774: enhancement(kicks): reduce spam of kick state

### LINKED ISSUE #785: feat(instant meeting, kicks): instant meetings should reset kicks
pending #780 #378

### PR DESCRIPTION
**Pull request by pikulet**
Fixes #785 
Fixes #774 

**starting the instant meeting resets kicks**
- [x] proposing resets kicks
- [x] accepting the proposal (finishing the instant meeting) does not reset kicks
- [x] after accepting the proposal, the target can kick

**made bride meeting veggable**

**fixed the kicking 2/2 spam we saw yesterday**

### CODE REVIEW

File: Games/core/VegKickMeeting.js [hunk 1]
```diff
@@ -12,6 +12,9 @@ module.exports = class VegKickMeeting extends Meeting {
         this.inputType = "button";
         this.targets = ["Kick"];
         this.votesInvisible = true;
+        // when enough kicks has reached, people who have not voted can spam kick
```
Comment (pikulet) [inline Games/core/VegKickMeeting.js:15]: This is because the game does not accept the person's vote as valid, allowing them to vote an unlimited number of times.

File: Games/core/VegKickMeeting.js [hunk 2]
```diff
@@ -24,9 +27,14 @@ module.exports = class VegKickMeeting extends Meeting {
 
     resetKicks() {
         this.game.clearTimer("vegKick");
-        this.votes = {};
+        this.finished = false;
 
         for (let player of this.game.players) {
+            // unvote
```
Comment (pikulet) [inline Games/core/VegKickMeeting.js:33]: a proper unvote is required for the frontend to see the unvote

File: Games/core/VegKickMeeting.js [hunk 3]
```diff
@@ -96,6 +104,7 @@ module.exports = class VegKickMeeting extends Meeting {
         let vegKickThreshold = Math.ceil(numAlive / 3);
 
         let numKicked = Object.keys(this.votes).length;
+        numKicked = Math.min(numKicked, vegKickThreshold);
```
Comment (pikulet) [inline Games/core/VegKickMeeting.js:107]: since now more people can kick than the threshold, this prevents that chat showing 3/2 4/2 and caps it at 2/2

**Review by starryburst — APPROVED** [review]

**Review by DrSharky — APPROVED** [review]
