### PR TITLE
fix: santa message is consistent with other roles

### LINKED ISSUE #799: bug(santa): misspelling
image

received is misspelled

you can also use queueGetItemAlert to standardise the icon

### PR DESCRIPTION
**Pull request by pikulet**
Fixes #799 

currently santa messages have the "gift" icon instead of gun/ armour etc

### CODE REVIEW

File: Games/types/Mafia/roles/cards/GivePresents.js [hunk 1]
```diff
@@ -15,11 +15,12 @@ module.exports = class GivePresents extends Card {
                     priority: PRIORITY_ITEM_GIVER_DEFAULT,
                     run: function() {
                         let itemType = this.actor.role.data.itemType;
-                        if (itemType){
-                            let alert = `:sy3a: You have recieved ${(itemType === "Armor" ? itemType : "a " + itemType).toLowerCase()}!`
```
Comment (pikulet) [inline Games/types/Mafia/roles/cards/GivePresents.js:19]: currently santa gifts have the present instead of gun icon etc...
